spring:
  application:
    name: orders-service-1

  # Подключение к БД
  datasource:
    url: jdbc:postgresql://postgres-orders-service-1:5432/orders-service-1-db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

    # Отключаем поведение open in view, при котором hibernate-сессии продлеваются на обработку всего HTTP-запроса
    open-in-view: false

  # Путь к версиям БД
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/master-changelog.xml

  # Kafka producer
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://schema-registry:8081
        auto.register.schemas: true
        specific.avro.reader: true

server:
  port: 8001

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    baggage:
      remote-fields: traceparent,tracestate
    propagation:
      type: w3c,b3

  otlp:  # ← otlp на одном уровне с tracing!
    tracing:
      endpoint: http://jaeger:4318/v1/traces

  metrics:
    export:
      otlp:
        enabled: false

  endpoints:
    web:
      exposure:
        include: health,info,prometheus

app:
  kafka:
    topic: reservation-order-topic

logging:
  level:
    # OpenTelemetry отладка
    io.opentelemetry: DEBUG
    io.opentelemetry.exporter: DEBUG
    io.opentelemetry.sdk: DEBUG

    # Micrometer Tracing отладка
    io.micrometer.tracing: DEBUG
    io.micrometer.tracing.otel: DEBUG

    # Kafka propagation отладка
    org.springframework.kafka: DEBUG

  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} [traceId=%X{traceId:-}, spanId=%X{spanId:-}] - %msg%n'