spring:
  application:
    name: products-service-2

  # Подключение к БД
  datasource:
    url: jdbc:postgresql://postgres-products-service-2:5432/products-service-2-db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

    # Отключаем поведение open in view, при котором hibernate-сессии продлеваются на обработку всего HTTP-запроса
    open-in-view: false

  # Путь к версиям БД
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/master-changelog.xml

  # Kafka consumer
  kafka:
    bootstrap-servers: kafka:9092
    listener:
      ack-mode: manual
    consumer:
      group-id: products-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      enable-auto-commit: false
      auto-offset-reset: earliest
      properties:
        schema.registry.url: http://schema-registry:8081
        auto.register.schemas: true
        specific.avro.reader: true
        spring:
          json:
            trusted:
              packages: "com.example.kafka.avro"

server:
  port: 8002

app:
  kafka:
    consumer:
      topics:
        reservation-topic: reservation-order-topic
      group-id: reservation-order-group

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    baggage:
      remote-fields: traceparent,tracestate
    propagation:
      type: w3c

  otlp:  # ← otlp на одном уровне с tracing!
    tracing:
      endpoint: http://jaeger:4318/v1/traces

  metrics:
    export:
      otlp:
        enabled: false

  endpoints:
    web:
      exposure:
        include: health,info,prometheus

logging:
  level:
    # OpenTelemetry отладка
    io.opentelemetry: DEBUG
    io.opentelemetry.exporter: DEBUG
    io.opentelemetry.sdk: DEBUG

    # Micrometer Tracing отладка
    io.micrometer.tracing: DEBUG
    io.micrometer.tracing.otel: DEBUG

    # Kafka propagation отладка
    org.springframework.kafka: DEBUG

  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} [traceId=%X{traceId:-}, spanId=%X{spanId:-}] - %msg%n'